services:
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: laravel_app_onfly
    volumes:
      - ./app:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - db
    networks:
      - onfly-network

  webserver:
    image: nginx:alpine
    container_name: laravel_web_onfly
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - onfly-network

  db:
    image: mysql:8.0
    container_name: laravel_db_onfly
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - onfly-network

  frontend:
    build:
      context: ./frontend
    container_name: vue_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - onfly-network

volumes:
  dbdata:

networks:
  onfly-network:
    driver: bridge
